export const REGISTER_USER_SUCCEED = 'REGISTER_USER_SUCCEED';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_USER_SUCCEED = 'LOGIN_USER_SUCCEED';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const AUTH_USER_SUCCEED = 'AUTH_USER_SUCCEED';
// export const AUTH_USER_FAIL = 'AUTH_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_CATEGORIES_DATA_SUCCEED = 'FETCH_CATEGORIES_DATA_SUCCEED';
export const FETCH_CATEGORIES_DATA_FAIL = 'FETCH_CATEGORIES_DATA_FAIL';
